const DAYS = 30;
const FUTURE_DAYS = 30;
const PREFETCH_DAYS = 90;
const CHUNK_SIZE = 7;
const prefectures = [
  ["北海道", "札幌市", 43.0642, 141.3469], ["青森県", "青森市", 40.8244, 140.74], ["岩手県", "盛岡市", 39.7036, 141.1527],
  ["宮城県", "仙台市", 38.2682, 140.8694], ["秋田県", "秋田市", 39.7186, 140.1024], ["山形県", "山形市", 38.2404, 140.3633],
  ["福島県", "福島市", 37.75, 140.4678], ["茨城県", "水戸市", 36.3418, 140.4468], ["栃木県", "宇都宮市", 36.5658, 139.8836],
  ["群馬県", "前橋市", 36.3911, 139.0608], ["埼玉県", "さいたま市", 35.8569, 139.6489], ["千葉県", "千葉市", 35.6046, 140.1233],
  ["東京都", "新宿区", 35.6895, 139.6917], ["神奈川県", "横浜市", 35.4478, 139.6425], ["新潟県", "新潟市", 37.9024, 139.0232],
  ["富山県", "富山市", 36.6953, 137.2113], ["石川県", "金沢市", 36.5944, 136.6256], ["福井県", "福井市", 36.0652, 136.2216],
  ["山梨県", "甲府市", 35.6639, 138.5683], ["長野県", "長野市", 36.6513, 138.181], ["岐阜県", "岐阜市", 35.3912, 136.7223],
  ["静岡県", "静岡市", 34.9769, 138.3831], ["愛知県", "名古屋市", 35.1802, 136.9066], ["三重県", "津市", 34.7303, 136.5086],
  ["滋賀県", "大津市", 35.0179, 135.8546], ["京都府", "京都市", 35.0116, 135.7681], ["大阪府", "大阪市", 34.6937, 135.5023],
  ["兵庫県", "神戸市", 34.6913, 135.183], ["奈良県", "奈良市", 34.6851, 135.8048], ["和歌山県", "和歌山市", 34.226, 135.1675],
  ["鳥取県", "鳥取市", 35.5037, 134.2383], ["島根県", "松江市", 35.4723, 133.0505], ["岡山県", "岡山市", 34.6618, 133.935],
  ["広島県", "広島市", 34.3853, 132.4553], ["山口県", "山口市", 34.1785, 131.4737], ["徳島県", "徳島市", 34.0658, 134.5593],
  ["香川県", "高松市", 34.3401, 134.0434], ["愛媛県", "松山市", 33.8417, 132.7661], ["高知県", "高知市", 33.5597, 133.5311],
  ["福岡県", "福岡市", 33.6064, 130.4181], ["佐賀県", "佐賀市", 33.2494, 130.2988], ["長崎県", "長崎市", 32.7448, 129.8737],
  ["熊本県", "熊本市", 32.8031, 130.7079], ["大分県", "大分市", 33.2382, 131.6126], ["宮崎県", "宮崎市", 31.9111, 131.4239],
  ["鹿児島県", "鹿児島市", 31.5602, 130.5581], ["沖縄県", "那覇市", 26.2124, 127.6809]
];
const weatherMap = {0:"晴れ",1:"主に晴れ",2:"晴れ時々くもり",3:"くもり",45:"霧",48:"霧氷",51:"霧雨",53:"霧雨",55:"霧雨",61:"雨",63:"雨",65:"雨",71:"雪",73:"雪",75:"雪",80:"にわか雨",81:"にわか雨",82:"にわか雨",95:"雷雨"};
const sel=document.getElementById("prefectureSelect"),btn=document.getElementById("loadButton"),statusEl=document.getElementById("status");
const toggleLastYear=document.getElementById("toggleLastYear"),toggleTwoYears=document.getElementById("toggleTwoYears"),toggleRawSeries=document.getElementById("toggleRawSeries");
const prevMonthBtn=document.getElementById("prevMonth"),nextMonthBtn=document.getElementById("nextMonth");
let dailyChart,compareChart,yearDiffChart,comparePayload,selectedLat,selectedLon,monthOffset=0,dailyRows=[],visibleCount=0,isAppending=false;
const f1=(n)=>Number.isFinite(n)?n.toFixed(1):"-",fmtDate=(d)=>d.toISOString().slice(0,10),shifted=(d,y)=>new Date(Date.UTC(d.getUTCFullYear()-y,d.getUTCMonth(),d.getUTCDate())),addDays=(d,days)=>{const r=new Date(d);r.setUTCDate(r.getUTCDate()+days);return r;};
const buildEl=document.getElementById("buildInfo");
function setBuildInfo(){const sha=(window.BUILD_SHA||"-").slice(0,7);buildEl.textContent=`build: v0.1.6 / ${sha||"-"}`;}
function fillPrefectures(){prefectures.forEach(([pref,city])=>{const o=document.createElement("option");o.value=pref;o.textContent=`${pref} / ${city}`;sel.appendChild(o);});sel.value="栃木県";}
async function fetchDaily(lat, lon, start, end, mode="archive"){const base=mode==="forecast"?"https://api.open-meteo.com/v1/forecast":"https://archive-api.open-meteo.com/v1/archive";const url=`${base}?latitude=${lat}&longitude=${lon}&start_date=${fmtDate(start)}&end_date=${fmtDate(end)}&daily=weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,shortwave_radiation_sum&timezone=Asia%2FTokyo`;const res=await fetch(url);if(!res.ok)throw new Error("fetch failed");return (await res.json()).daily;}
function hideSections(){["summaryCards","chartSection","tableSection","futureCompareSection","yearDiffSection"].forEach(id=>document.getElementById(id).hidden=true);}
async function loadData(){const picked=prefectures.find(([p])=>p===sel.value);if(!picked)return;const[pref,city,lat,lon]=picked;selectedLat=lat;selectedLon=lon;monthOffset=0;statusEl.textContent="データ取得中...";btn.disabled=true;try{const end=new Date(),start=addDays(end,-(DAYS-1));const thisYear=await fetchDaily(lat,lon,start,end);renderMain(pref,city,thisYear);await renderDailyRows(lat,lon);await renderFutureCompare(lat,lon,start);await renderYearDiff();statusEl.textContent="";}catch{hideSections();statusEl.textContent="データを取得できませんでした";statusEl.className="status error";}finally{btn.disabled=false;}}
function renderMain(pref,city,daily){const rows=daily.time.map((date,i)=>({date,rad:daily.shortwave_radiation_sum[i],tavg:daily.temperature_2m_mean[i]}));document.getElementById("selectedLocation").textContent=`${pref} / ${city}`;document.getElementById("summaryCards").hidden=false;const ctx=document.getElementById("dailyChart");if(dailyChart)dailyChart.destroy();dailyChart=new Chart(ctx,{type:"line",data:{labels:rows.map(r=>r.date.slice(5)),datasets:[{label:"日射量 MJ/㎡/日",data:rows.map(r=>r.rad),yAxisID:"yRad",borderColor:"#d62728",backgroundColor:"#d62728",tension:.25},{label:"1日平均気温 ℃",data:rows.map(r=>Number(f1(r.tavg))),yAxisID:"yTemp",borderColor:"#1f77b4",backgroundColor:"#1f77b4",tension:.25}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{display:true}},scales:{yRad:{type:"linear",position:"left"},yTemp:{type:"linear",position:"right",grid:{drawOnChartArea:false}}}}});document.getElementById("chartSection").hidden=false;}
async function renderDailyRows(lat,lon){const now=new Date();const future=addDays(now,PREFETCH_DAYS);const daily=await fetchDaily(lat,lon,now,future,"forecast");dailyRows=daily.time.map((date,i)=>({date,weather:weatherMap[daily.weather_code[i]]??`コード${daily.weather_code[i]}`,rad:daily.shortwave_radiation_sum[i],tmax:daily.temperature_2m_max[i],tmin:daily.temperature_2m_min[i],tavg:daily.temperature_2m_mean[i]}));visibleCount=0;document.getElementById("dataTableBody").innerHTML="";appendRows();document.getElementById("tableSection").hidden=false;}
function appendRows(){if(isAppending)return;isAppending=true;document.getElementById("dailyLoading").hidden=false;setTimeout(()=>{const next=Math.min(visibleCount+CHUNK_SIZE,dailyRows.length);const chunk=dailyRows.slice(visibleCount,next);const html=chunk.map(r=>{const m=Number(r.date.slice(5,7));const d=Number(r.date.slice(8,10));return `<tr><td>${m}/${d}</td><td>${r.weather}</td><td>${f1(r.rad)}</td><td>${f1(r.tmax)}</td><td>${f1(r.tmin)}</td><td>${f1(r.tavg)}</td></tr>`;}).join("");document.getElementById("dataTableBody").insertAdjacentHTML("beforeend",html);visibleCount=next;document.getElementById("dailyLoading").hidden=true;document.getElementById("dailyEnd").hidden=visibleCount<dailyRows.length;isAppending=false;},200);}
window.addEventListener("scroll",()=>{if(document.getElementById("tableSection").hidden||isAppending)return;const nearBottom=window.innerHeight+window.scrollY>=document.body.offsetHeight-220;if(nearBottom&&visibleCount<dailyRows.length)appendRows();});
function movingAverage7(data){return data.map((_,idx)=>{const start=Math.max(0,idx-6);const window=data.slice(start,idx+1).filter(v=>Number.isFinite(v));return window.length?Number((window.reduce((a,b)=>a+b,0)/window.length).toFixed(2)):null;});}
async function renderFutureCompare(lat,lon,start){const compareError=document.getElementById("compareError");compareError.hidden=true;try{const compareStart=start,compareEnd=addDays(start,FUTURE_DAYS-1);const [lastYear,twoYears]=await Promise.all([fetchDaily(lat,lon,shifted(compareStart,1),shifted(compareEnd,1)),fetchDaily(lat,lon,shifted(compareStart,2),shifted(compareEnd,2))]);const labels=[...Array(FUTURE_DAYS)].map((_,i)=>fmtDate(addDays(compareStart,i)).slice(5));comparePayload={labels,lastYearData:lastYear.shortwave_radiation_sum,twoYearsData:twoYears.shortwave_radiation_sum,year1:compareStart.getUTCFullYear()-1,year2:compareStart.getUTCFullYear()-2};drawCompareChart();document.getElementById("futureCompareSection").hidden=false;}catch{if(compareChart)compareChart.destroy();document.getElementById("futureCompareSection").hidden=false;compareError.hidden=false;}}
function drawCompareChart(){if(!comparePayload)return;const datasets=[];const raw=toggleRawSeries.checked;const push=(enabled,name,rawName,data,color)=>{if(!enabled)return;datasets.push({label:`${name} 7日平均`,data:movingAverage7(data),borderColor:color,backgroundColor:color,tension:.25,borderWidth:2.5,pointRadius:0});if(raw)datasets.push({label:`${rawName}（日別）`,data,borderColor:color,backgroundColor:color,tension:.12,borderDash:[5,4],borderWidth:1.2,pointRadius:1});};push(toggleLastYear.checked,`${comparePayload.year1}年`,`${comparePayload.year1}年`,comparePayload.lastYearData,"#ff7f0e");push(toggleTwoYears.checked,`${comparePayload.year2}年`,`${comparePayload.year2}年`,comparePayload.twoYearsData,"#9467bd");const ctx=document.getElementById("compareChart");if(compareChart)compareChart.destroy();compareChart=new Chart(ctx,{type:"line",data:{labels:comparePayload.labels,datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{display:true}}}});}
async function renderYearDiff(){const errorEl=document.getElementById("yearDiffError");errorEl.hidden=true;const baseStart=addDays(new Date(),monthOffset*30);const baseEnd=addDays(baseStart,29);try{const [y1,y2]=await Promise.all([fetchDaily(selectedLat,selectedLon,shifted(baseStart,1),shifted(baseEnd,1)),fetchDaily(selectedLat,selectedLon,shifted(baseStart,2),shifted(baseEnd,2))]);const labels=y1.time.map(t=>t.slice(5));const ctx=document.getElementById("yearDiffChart");if(yearDiffChart)yearDiffChart.destroy();yearDiffChart=new Chart(ctx,{type:"line",data:{labels,datasets:[{label:`${baseStart.getUTCFullYear()-1}年 7日平均`,data:movingAverage7(y1.shortwave_radiation_sum),borderColor:"#ff7f0e",backgroundColor:"#ff7f0e",tension:.25,borderWidth:2.5,pointRadius:0},{label:`${baseStart.getUTCFullYear()-2}年 7日平均`,data:movingAverage7(y2.shortwave_radiation_sum),borderColor:"#9467bd",backgroundColor:"#9467bd",tension:.25,borderWidth:2.5,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true}}}});document.getElementById("yearDiffSection").hidden=false;}catch{errorEl.hidden=false;document.getElementById("yearDiffSection").hidden=false;}}
setBuildInfo();fillPrefectures();btn.addEventListener("click",loadData);[toggleLastYear,toggleTwoYears,toggleRawSeries].forEach(el=>el.addEventListener("change",drawCompareChart));prevMonthBtn.addEventListener("click",()=>{monthOffset-=1;renderYearDiff();});nextMonthBtn.addEventListener("click",()=>{monthOffset+=1;renderYearDiff();});loadData();
