const DAYS = 30;
const FUTURE_DAYS = 30;
const prefectures = [
  ["北海道", "札幌市", 43.0642, 141.3469], ["青森県", "青森市", 40.8244, 140.74], ["岩手県", "盛岡市", 39.7036, 141.1527],
  ["宮城県", "仙台市", 38.2682, 140.8694], ["秋田県", "秋田市", 39.7186, 140.1024], ["山形県", "山形市", 38.2404, 140.3633],
  ["福島県", "福島市", 37.75, 140.4678], ["茨城県", "水戸市", 36.3418, 140.4468], ["栃木県", "宇都宮市", 36.5658, 139.8836],
  ["群馬県", "前橋市", 36.3911, 139.0608], ["埼玉県", "さいたま市", 35.8569, 139.6489], ["千葉県", "千葉市", 35.6046, 140.1233],
  ["東京都", "新宿区", 35.6895, 139.6917], ["神奈川県", "横浜市", 35.4478, 139.6425], ["新潟県", "新潟市", 37.9024, 139.0232],
  ["富山県", "富山市", 36.6953, 137.2113], ["石川県", "金沢市", 36.5944, 136.6256], ["福井県", "福井市", 36.0652, 136.2216],
  ["山梨県", "甲府市", 35.6639, 138.5683], ["長野県", "長野市", 36.6513, 138.181], ["岐阜県", "岐阜市", 35.3912, 136.7223],
  ["静岡県", "静岡市", 34.9769, 138.3831], ["愛知県", "名古屋市", 35.1802, 136.9066], ["三重県", "津市", 34.7303, 136.5086],
  ["滋賀県", "大津市", 35.0179, 135.8546], ["京都府", "京都市", 35.0116, 135.7681], ["大阪府", "大阪市", 34.6937, 135.5023],
  ["兵庫県", "神戸市", 34.6913, 135.183], ["奈良県", "奈良市", 34.6851, 135.8048], ["和歌山県", "和歌山市", 34.226, 135.1675],
  ["鳥取県", "鳥取市", 35.5037, 134.2383], ["島根県", "松江市", 35.4723, 133.0505], ["岡山県", "岡山市", 34.6618, 133.935],
  ["広島県", "広島市", 34.3853, 132.4553], ["山口県", "山口市", 34.1785, 131.4737], ["徳島県", "徳島市", 34.0658, 134.5593],
  ["香川県", "高松市", 34.3401, 134.0434], ["愛媛県", "松山市", 33.8417, 132.7661], ["高知県", "高知市", 33.5597, 133.5311],
  ["福岡県", "福岡市", 33.6064, 130.4181], ["佐賀県", "佐賀市", 33.2494, 130.2988], ["長崎県", "長崎市", 32.7448, 129.8737],
  ["熊本県", "熊本市", 32.8031, 130.7079], ["大分県", "大分市", 33.2382, 131.6126], ["宮崎県", "宮崎市", 31.9111, 131.4239],
  ["鹿児島県", "鹿児島市", 31.5602, 130.5581], ["沖縄県", "那覇市", 26.2124, 127.6809]
];
const weatherMap = {0:"晴れ",1:"主に晴れ",2:"晴れ時々くもり",3:"くもり",45:"霧",48:"霧氷",51:"霧雨",53:"霧雨",55:"霧雨",61:"雨",63:"雨",65:"雨",71:"雪",73:"雪",75:"雪",80:"にわか雨",81:"にわか雨",82:"にわか雨",95:"雷雨"};
const sel=document.getElementById("prefectureSelect"),btn=document.getElementById("loadButton"),statusEl=document.getElementById("status");
const toggleThisYear=document.getElementById("toggleThisYear"),toggleLastYear=document.getElementById("toggleLastYear"),toggleTwoYears=document.getElementById("toggleTwoYears");
const tableToggleBtn=document.getElementById("toggleTableButton");
let dailyChart,compareChart,comparePayload;
let allTableRows=[];
let isTableExpanded=false;
const f1=(n)=>Number.isFinite(n)?n.toFixed(1):"-",fmtDate=(d)=>d.toISOString().slice(0,10),shifted=(d,y)=>new Date(Date.UTC(d.getUTCFullYear()-y,d.getUTCMonth(),d.getUTCDate())),addDays=(d,days)=>{const r=new Date(d);r.setUTCDate(r.getUTCDate()+days);return r;};
function fillPrefectures(){prefectures.forEach(([pref,city])=>{const o=document.createElement("option");o.value=pref;o.textContent=`${pref} / ${city}`;sel.appendChild(o);});sel.value="栃木県";}
async function fetchDaily(lat, lon, start, end){const url=`https://archive-api.open-meteo.com/v1/archive?latitude=${lat}&longitude=${lon}&start_date=${fmtDate(start)}&end_date=${fmtDate(end)}&daily=weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,shortwave_radiation_sum&timezone=Asia%2FTokyo`;const res=await fetch(url);if(!res.ok)throw new Error("fetch failed");return (await res.json()).daily;}
function hideSections(){["summaryCards","chartSection","tableSection","compareSection","futureTableSection"].forEach(id=>document.getElementById(id).hidden=true);}
async function loadData(){const picked=prefectures.find(([p])=>p===sel.value);if(!picked)return;const[pref,city,lat,lon]=picked;statusEl.textContent="データ取得中...";statusEl.className="status";btn.disabled=true;try{const end=new Date(),start=addDays(end,-(DAYS-1));const thisYear=await fetchDaily(lat,lon,start,end);renderMain(pref,city,thisYear);await renderCompareAndFuture(lat,lon,start,end,thisYear);statusEl.textContent="";}catch{hideSections();statusEl.textContent="データを取得できませんでした";statusEl.className="status error";}finally{btn.disabled=false;}}
function renderMain(pref,city,daily){const rows=daily.time.map((date,i)=>({date,weather:weatherMap[daily.weather_code[i]]??`コード${daily.weather_code[i]}`,rad:daily.shortwave_radiation_sum[i],tmax:daily.temperature_2m_max[i],tmin:daily.temperature_2m_min[i],tavg:daily.temperature_2m_mean[i]}));const latest=rows[rows.length-1];document.getElementById("selectedLocation").textContent=`${pref} / ${city}`;document.getElementById("todaySummary").textContent=`${latest.weather} / 日射 ${f1(latest.rad)} / 平均 ${f1(latest.tavg)}℃`;document.getElementById("summaryCards").hidden=false;drawChart(rows);renderTable(rows.slice().reverse());}
function drawChart(rows){const ctx=document.getElementById("dailyChart");if(dailyChart)dailyChart.destroy();dailyChart=new Chart(ctx,{type:"line",data:{labels:rows.map(r=>r.date.slice(5)),datasets:[{label:"日射量 MJ/㎡/日",data:rows.map(r=>r.rad),yAxisID:"yRad",borderColor:"#d62728",backgroundColor:"#d62728",tension:.25},{label:"1日平均気温 ℃",data:rows.map(r=>Number(f1(r.tavg))),yAxisID:"yTemp",borderColor:"#1f77b4",backgroundColor:"#1f77b4",tension:.25}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{display:true}},scales:{yRad:{type:"linear",position:"left"},yTemp:{type:"linear",position:"right",grid:{drawOnChartArea:false}}}}});document.getElementById("chartSection").hidden=false;}
function renderTable(rows){allTableRows=rows;isTableExpanded=false;updateTableRows();document.getElementById("tableSection").hidden=false;}
function updateTableRows(){const visibleRows=isTableExpanded?allTableRows:allTableRows.slice(0,7);document.getElementById("dataTableBody").innerHTML=visibleRows.map(r=>{const m=Number(r.date.slice(5,7));const d=Number(r.date.slice(8,10));return `<tr><td>${m}/${d}</td><td>${r.weather}</td><td>${f1(r.rad)}</td><td>${f1(r.tmax)}</td><td>${f1(r.tmin)}</td><td>${f1(r.tavg)}</td></tr>`;}).join("");if(allTableRows.length>7){tableToggleBtn.hidden=false;tableToggleBtn.textContent=isTableExpanded?"閉じる":"もっと見る";}else{tableToggleBtn.hidden=true;}}
async function renderCompareAndFuture(lat,lon,start,end,thisYear){const compareError=document.getElementById("compareError");compareError.hidden=true;const compareStart=start,compareEnd=addDays(end,FUTURE_DAYS);try{const [lastYear,twoYears]=await Promise.all([fetchDaily(lat,lon,shifted(compareStart,1),shifted(compareEnd,1)),fetchDaily(lat,lon,shifted(compareStart,2),shifted(compareEnd,2))]);const nowYear=new Date().getFullYear();document.getElementById("lastYearHeader").textContent=`${nowYear-1}日射量`;document.getElementById("twoYearsHeader").textContent=`${nowYear-2}日射量`;const labels=[...Array(DAYS+FUTURE_DAYS)].map((_,i)=>fmtDate(addDays(compareStart,i)).slice(5));const thisMap=Object.fromEntries(thisYear.time.map((t,i)=>[t,thisYear.shortwave_radiation_sum[i]]));comparePayload={labels,thisYearData:[...Array(DAYS+FUTURE_DAYS)].map((_,i)=>thisMap[fmtDate(addDays(compareStart,i))]??null),lastYearData:lastYear.shortwave_radiation_sum,twoYearsData:twoYears.shortwave_radiation_sum};drawCompareChart();renderFutureTable(compareStart,lastYear,twoYears);document.getElementById("compareSection").hidden=false;}catch{if(compareChart)compareChart.destroy();document.getElementById("compareSection").hidden=false;compareError.hidden=false;document.getElementById("futureTableSection").hidden=true;}}
function drawCompareChart(){if(!comparePayload)return;const datasets=[];if(toggleThisYear.checked)datasets.push({label:"今年の日射量（実績）",data:comparePayload.thisYearData,borderColor:"#d62728",backgroundColor:"#d62728",tension:.25,spanGaps:false});if(toggleLastYear.checked)datasets.push({label:"昨年の日射量",data:comparePayload.lastYearData,borderColor:"#ff7f0e",backgroundColor:"#ff7f0e",tension:.25});if(toggleTwoYears.checked)datasets.push({label:"2年前の日射量",data:comparePayload.twoYearsData,borderColor:"#9467bd",backgroundColor:"#9467bd",tension:.25});const ctx=document.getElementById("compareChart");if(compareChart)compareChart.destroy();compareChart=new Chart(ctx,{type:"line",data:{labels:comparePayload.labels,datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{display:true}}}});}
function renderFutureTable(compareStart,lastYear,twoYears){const body=document.getElementById("futureTableBody");body.innerHTML=[...Array(FUTURE_DAYS)].map((_,i)=>{const idx=DAYS+i;const d=addDays(compareStart,idx);return `<tr><td>${d.getUTCMonth()+1}/${d.getUTCDate()}</td><td>${f1(lastYear.shortwave_radiation_sum[idx])}</td><td>${f1(twoYears.shortwave_radiation_sum?.[idx])}</td></tr>`;}).join("");document.getElementById("futureTableSection").hidden=false;}
fillPrefectures();btn.addEventListener("click",loadData);[toggleThisYear,toggleLastYear,toggleTwoYears].forEach(el=>el.addEventListener("change",drawCompareChart));loadData();
tableToggleBtn.addEventListener("click",()=>{isTableExpanded=!isTableExpanded;updateTableRows();});
